[package]
name = "rust-send2"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dora-node-api = { version = "0.3.4", features = ["tracing"] }
eyre = "0.6.8"
